### ISSUE TITLE
Figure out why req$ arguments linger between requests.

### ISSUE THREAD

**Issue by trestletech** [trestletech/rapier#12]
I think it's a bug in httpuv. Come up with a workaround and report it if so.

**Comment by trestletech** [comment]
https://github.com/trestletech/rapier/blob/master/R/rapier.R#L185-L187

**Comment by trestletech** [comment]
https://github.com/rstudio/httpuv/issues/49

**Comment by codecheetos** [comment]
With a simple httpuv listener, setting the HTTP_CONNECTION to "close" did the trick. By default the connection is set to "Keep-Alive".

`req$HTTP_CONNECTION <- 'close'`

**Comment by codecheetos** [comment]
Is there plans to fix this issue in future?

**Comment by trestletech** [comment]
We "solved" this using the same approach you suggested above in https://github.com/trestletech/plumber/blob/f292ef032aa58ae2871edbd9be60e720698dc5b8/R/response.R#L25-L27 which is how I closed the ticket.

But the underlying issue in httpuv is still open and is being tracked here: https://github.com/rstudio/httpuv/issues/49
