### ISSUE TITLE
Add REST-style abstractions in URL matching

### ISSUE THREAD

**Issue by trestletech** [trestletech/rapier#13]
Support something like `@get /cars/:id` where `id` because a parameter passed in to the function.

**Comment by trestletech** [comment]
http://www.sinatrarb.com/intro.html for additional formats perhaps worth supporting.

In this case, seems like convention is just to pass those params in as strings.

**Comment by sckott** [comment]
In my experience there's lots of APIs that use a format like `@get /cars/:id` - instead of `id` being a query parameter - possible to support `@get /cars/:id`?

**Comment by trestletech** [comment]
Totally, I just used the bracket syntax so you could more easily specify the expected type of the param. So it would be `@get /cars/<id>` or `@get/cars/<id:int>` if you wanted to save yourself an `as.numeric()`. http://plumber.trestletech.com/docs/routing/

**Comment by sckott** [comment]
thanks :)
